version: '3'
services:

  # To be filled in further, if necessary
  app:
    build:
      dockerfile: Dockerfile
      context: .
    links:
      - redis
      - answer

  # A simple HTTP server to verify the checksum is correct
  answer:
    build:
      context: .
      dockerfile: Dockerfile.server
    command: node answer.js
    ports:
      - 3000:3000

  # Utility to verify the database is in its intended state
  # docker-compose up verify
  verify:
    build:
      context: .
      dockerfile: Dockerfile.server
    links:
      - redis
      - answer
    command: node verify.js

  # The redis database populated from data in ./data
  redis:
    image: 'redis:3.2.11-alpine'
    ports:
      - 6379:6379
    volumes:
      - ./data:/data
